### ISSUE TITLE
get the device that is connected

### ISSUE THREAD

**Issue by Deboracgs** [Spayker/rn-miband-connector#11]
How to get the device already connected? I will leave the service in the background and I will get the data to play in an api, but for example, I access the app and I want to show the device that is already connected so that I can disconnect and connect another ... I reloaded the app and I saw that it's still connected, but I can't search anymore

**Comment by Spayker** [comment]
"How to get the device already connected?" - once you have connected to miband it stays connected until BlueTooth connection is interrupted.

"I want to show the device that is already connected" - async storage can help you to keep data about successful connection. If you want to get some confirmation from device directly then you can send request to device to get auth based data (f.e. get steps or get callories)
