### ISSUE TITLE
I am not found User token and other detatils

### ISSUE THREAD

**Issue by VijaySharma12** [Spayker/rn-miband-connector#14]
Please provide me detail for this keys:-
    **SERVER_AUTH_URL_ADDRESS: '192.168.8.118:5000',
    SERVER_ACCOUNT_URL_ADDRESS: '192.168.8.118:6000',
    SERVER_DEVICE_URL_ADDRESS: '192.168.8.118:7000',

    // Async Storage Keys
    ACCESS_TOKEN_KEY: '@AccessToken',
    USERNAME_TOKEN_KEY: '@UserName',
    DEVICE_ID_KEY: '@DeviceId',

    // AUTH PROCESS DATA
    AUTHORIZED_STATE: 'authorized',
    UNAUTHORIZED_STATE: 'unauthorized'**

How we can get this details for my application ?

**Comment by Spayker** [comment]
First of all, you need to setup and run that server locally. If it's done properly you will have access to **auth**, **account** and **device** services by mentioned **ports**. That should be enough for your connector to begin communication with server side and get appropriate tokens.

**Comment by VijaySharma12** [comment]
What server in application ? I want to only measurement for BP ,Heart Rate.

**Comment by Spayker** [comment]
Read project description carefully: there is one reference to server side project: https://github.com/Spayker/rn-miband-connector-server
