### ISSUE TITLE
Q: NFC version

### ISSUE THREAD

**Issue by st-schneider** [Spayker/rn-miband-connector#3]
Would it be possible to enable NFC for outside of china with the connector?

**Comment by Spayker** [comment]
Good question. It's not easy to answer it since I have only 3-rd version of miBand where NFC not included.

I'm about to buy 4-th version this month and check it.

**Comment by st-schneider** [comment]
there is a 3rd version of miband with nfc https://www.youtube.com/watch?v=SQgYMKx7Nls

**Comment by st-schneider** [comment]
btw I have one, that's why I'm asking

**Comment by st-schneider** [comment]
> NFC function only applies to China

**Comment by Spayker** [comment]
Wow, did not know that. Have a feeling it won't work cause of firmware version and connector uses a standard set of services miBand provides.

**Comment by st-schneider** [comment]
how does the thing even get to know it is outside china?

**Comment by Spayker** [comment]
I guess it depends on firmware version
