### ISSUE TITLE
Compatible with miband 4

### ISSUE THREAD

**Issue by kukuandroid** [Spayker/rn-miband-connector#7]
Thank you for the solution. I tested with miband 4 . Do you find it working? Thanksss

**Comment by Spayker** [comment]
Hello. Sorry for late reply...

I have not yet tested it with MiBand 4 seriously.
Last founds showed an auth process was changed in 4-th version. My solution can't use generate a key this time to proceed with pairing. That problematic key is supplied by Xiaomi auth server as far as I remember. Finally it must be stored at sqlite db...
