### ISSUE TITLE
error - connected but not paired

### ISSUE THREAD

**Issue by Deboracgs** [Spayker/rn-miband-connector#9]
when I click on the "Link to band" button, it is loading and after a few minutes the loading disappears and enables the 'Start HR measurement' button, but when I click on this button, this error appears.

![Screenshot_2020-05-27-22-10-49-366](https://user-images.githubusercontent.com/12396210/83073768-e3f8d580-a068-11ea-9303-b0de541a3bfe.jpeg)

**Comment by Spayker** [comment]
Smells like a bug :)

If it does not connect to certain device usually battery value will be zero still. So start HR measurement button must stay in disabled mode.

**Comment by Deboracgs** [comment]
Hmm I will change the logic of enable button to see if it works

**Comment by Spayker** [comment]
I believe it connects to your device and bond level will be around 10. Meanwhile it's not paired yet but 'start HR measurement' has been already pressed. We know such operations require already ended paired procedure. That is why it returns null in setValue method...

**Comment by Spayker** [comment]
Issue was solved in latest merged PR
